ddad:
    crop: ''
    min_depth: 0.0
    max_depth: 200.0
    scale_output: resize
    post_process: False
    cam_batch_median_scaling: True
nuscenes:
    crop: ''
    min_depth: 0.1
    max_depth: 80.0
    scale_output: resize
    post_process: False